using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Shared.Heretic;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Controls;
using Content.Shared.Heretic.Prototypes;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Shared.ContentPack;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Wega.Heretic.Ui;

[GenerateTypedNameReferences]
public sealed partial class HereticStoreMenu : HereticWindow
{
    public event Action<string>? OnBuyPressed;

    private static readonly Color CardBg   = Color.FromHex("#4A4068");
    private static readonly Color LockedBg = Color.FromHex("#342C48");
    private static readonly Color IconBg   = Color.FromHex("#2A2440");
    private static readonly Color BadgeBg  = Color.FromHex("#4A3A16");
    private static readonly Color TipBg = Color.FromHex("#383052");

    private static readonly Color OwnedStripe    = Color.FromHex("#D0AB5A");
    private static readonly Color AvailStripe    = Color.FromHex("#9A78D4");
    private static readonly Color LockedStripe   = Color.FromHex("#5A5176");
    private static readonly Color ConflictStripe = Color.FromHex("#A8404E");

    private static readonly Color NameCol    = Color.FromHex("#F0EAF6");
    private static readonly Color DescCol     = Color.FromHex("#B4ABC6");
    private static readonly Color LockedName  = Color.FromHex("#9A90AE");
    private static readonly Color LockedDesc  = Color.FromHex("#6E657C");
    private static readonly Color TierCol      = Color.FromHex("#C9A0EC");
    private static readonly Color TierLine     = Color.FromHex("#4A4068");
    private static readonly Color HeaderCol    = Color.FromHex("#9A90AE");
    private static readonly Color CaptionCol   = Color.FromHex("#B4ABC6");
    private static readonly Color GoldCol      = Color.FromHex("#ECC76E");
    private static readonly Color PathDimCol   = Color.FromHex("#9088A4");
    private static readonly Color RuneChosenBg = Color.FromHex("#4A3A16");
    private static readonly Color RuneDimBg    = Color.FromHex("#342C48");

    private readonly Dictionary<string, Color> _pathColors = new();

    private readonly IPrototypeManager _proto;
    private readonly SpriteSystem _sprite;
    private readonly IResourceCache _res;
    private readonly Texture _lockTex;
    private readonly Texture _checkTex;

    private readonly Font _fHeader;
    private readonly Font _fTier;
    private readonly Font _fName;
    private readonly Font _fDesc;
    private readonly Font _fPoints;
    private readonly Font _fCaption;
    private readonly Font _fTipName;

    public HereticStoreMenu()
    {
        RobustXamlLoader.Load(this);

        var ent = IoCManager.Resolve<IEntityManager>();
        _sprite = ent.EntitySysManager.GetEntitySystem<SpriteSystem>();
        _proto = IoCManager.Resolve<IPrototypeManager>();
        _res = IoCManager.Resolve<IResourceCache>();

        _lockTex = _sprite.Frame0(new SpriteSpecifier.Texture(
            new ResPath("/Textures/Interface/VerbIcons/lock.svg.192dpi.png")));
        _checkTex = _sprite.Frame0(new SpriteSpecifier.Texture(
            new ResPath("/Textures/Interface/Nano/Monotone/monotone_checkbox_checked.svg.96dpi.png")));

        _fHeader  = Reg(12);
        _fTier    = Reg(12);
        _fName    = Reg(13);
        _fDesc    = Reg(11);
        _fPoints  = Bold(12);
        _fCaption = Reg(12);
        _fTipName = Bold(13);

        PointsCaption.Text = Loc.GetString("heretic-store-points-label");
        PointsCaption.FontOverride = _fCaption;
        PointsCaption.FontColorOverride = CaptionCol;
        PointsLabel.FontOverride = _fPoints;
        PointsLabel.FontColorOverride = GoldCol;

        TreeHeader.Text = Loc.GetString("heretic-store-tree");
        ShopHeader.Text = Loc.GetString("heretic-store-shop");
        TreeHeader.FontOverride = _fHeader;
        ShopHeader.FontOverride = _fHeader;
        TreeHeader.FontColorOverride = HeaderCol;
        ShopHeader.FontColorOverride = HeaderCol;
    }

    private Font Bold(int size)
        => new VectorFont(_res.GetResource<FontResource>("/Fonts/NotoSans/NotoSans-Bold.ttf"), size);

    private Font Reg(int size)
        => new VectorFont(_res.GetResource<FontResource>("/Fonts/NotoSans/NotoSans-Regular.ttf"), size);

    private Texture? NodeIcon(string id)
        => _proto.TryIndex<HereticKnowledgePrototype>(id, out var p) && p.Icon != null
            ? _sprite.Frame0(p.Icon) : null;

    private Texture? PathIcon(string id)
        => _proto.TryIndex<HereticPathPrototype>(id, out var p) && p.Icon != null
            ? _sprite.Frame0(p.Icon) : null;

    public void UpdateState(HereticStoreState state)
    {
        PointsLabel.Text = state.Points.ToString();

        var treeScroll = TreeScroll.GetScrollValue();
        var shopScroll = ShopScroll.GetScrollValue();

        RuneRow.RemoveAllChildren();
        TreeList.Children.Clear();
        ShopList.Children.Clear();

        _pathColors.Clear();
        foreach (var path in state.Paths)
            _pathColors[path.Id] = Color.FromHex(path.Color, AvailStripe);

        if (state.Paths.Count > 0)
            MakeRuneRow(state);

        var lastTree = int.MinValue;
        foreach (var node in state.Nodes.Where(n => n.Status == HereticNodeStatus.Owned).OrderBy(n => n.Stage))
        {
            if (node.Stage != lastTree)
            {
                lastTree = node.Stage;
                TreeList.AddChild(MakeTierLabel(node.Stage));
            }
            TreeList.AddChild(MakeCard(node, state.Points, isShop: false));
        }
        if (TreeList.ChildCount == 0)
            TreeList.AddChild(MakePlaceholder("heretic-store-tree-empty"));

        var lastShop = int.MinValue;
        foreach (var node in state.Nodes.Where(n => n.Status != HereticNodeStatus.Owned).OrderBy(n => n.Stage))
        {
            if (node.Stage != lastShop)
            {
                lastShop = node.Stage;
                ShopList.AddChild(MakeTierLabel(node.Stage));
            }
            ShopList.AddChild(MakeCard(node, state.Points, isShop: true));
        }
        if (ShopList.ChildCount == 0)
            ShopList.AddChild(MakePlaceholder("heretic-store-shop-empty"));

        TreeScroll.SetScrollValue(treeScroll);
        ShopScroll.SetScrollValue(shopScroll);
    }

    private void MakeRuneRow(HereticStoreState state)
    {
        var noPath = state.CurrentPath == null;

        var caption = new Label
        {
            FontOverride = _fCaption,
            FontColorOverride = noPath ? GoldCol : CaptionCol,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(0, 0, 10, 0),
        };
        if (noPath)
            caption.Text = Loc.GetString("heretic-store-path-none");
        else
        {
            var chosen = state.Paths.FirstOrDefault(p => p.Chosen);
            caption.Text = Loc.GetString("heretic-store-path", ("path", Loc.GetString(chosen.Name)));
        }
        RuneRow.AddChild(caption);

        foreach (var path in state.Paths)
        {
            var pathColor = Color.FromHex(path.Color, AvailStripe);

            var rune = new HereticPoly(path.Chosen ? RuneChosenBg : RuneDimBg)
            {
                Octagon = true,
                Icon = PathIcon(path.Id),
                Bevel = 8,
                BorderColor = path.Chosen ? pathColor : LockedStripe,
                BorderWidth = 2f,
                MinSize = new Vector2(38, 38),
                Margin = new Thickness(0, 0, 5, 0),
                ToolTip = Loc.GetString(path.Name),
            };

            if (!noPath && !path.Chosen)
                rune.Modulate = Color.White.WithAlpha(0.4f);

            if (noPath)
            {
                rune.Clickable = true;
                rune.MouseFilter = MouseFilterMode.Stop;
                rune.HoverBorder = pathColor;
                var entry = path.EntryNode;
                rune.OnPressed += () => OnBuyPressed?.Invoke(entry);
            }

            RuneRow.AddChild(rune);
        }
    }

    private Control MakeCard(HereticStoreNode node, int points, bool isShop)
    {
        var locked = node.Status == HereticNodeStatus.Locked;
        var conflicted = node.Status == HereticNodeStatus.Conflicted;
        var dim = locked || conflicted;
        var affordable = points >= node.Cost;
        var buyable = isShop && node.Status == HereticNodeStatus.Available && affordable;

        Color stripe;
        if (!isShop) stripe = node.Path != null && _pathColors.TryGetValue(node.Path, out var pc) ? pc : OwnedStripe;
        else if (conflicted) stripe = ConflictStripe;
        else if (locked) stripe = LockedStripe;
        else stripe = AvailStripe;

        var card = new HereticPoly(dim ? LockedBg : CardBg)
        {
            BorderColor = Color.Transparent,
            Stripe = stripe,
            HoverStripe = buyable ? GoldCol : null,
            StripeWidth = 3f,
            Bevel = 11,
            HorizontalExpand = true,
            Margin = new Thickness(2, 0, 2, 6),
        };

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(13, 8, 12, 8),
        };

        row.AddChild(new HereticPoly(IconBg)
        {
            Octagon = true,
            Bevel = 7,
            Icon = NodeIcon(node.Id),
            MinSize = new Vector2(28, 28),
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(0, 0, 9, 0),
        });

        var text = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };
        text.AddChild(new Label
        {
            Text = Loc.GetString(node.Name),
            FontOverride = _fName,
            FontColorOverride = dim ? LockedName : NameCol,
            ClipText = true,
        });
        if (!string.IsNullOrEmpty(node.Description))
        {
            text.AddChild(new Label
            {
                Text = Loc.GetString(node.Description),
                FontOverride = _fDesc,
                FontColorOverride = dim ? LockedDesc : DescCol,
                ClipText = true,
            });
        }
        row.AddChild(text);

        if (!isShop)
        {
            row.AddChild(new TextureRect
            {
                Texture = _checkTex,
                Stretch = TextureRect.StretchMode.Scale,
                SetSize = new Vector2(15, 15),
                Modulate = GoldCol,
                VerticalAlignment = VAlignment.Center,
            });
        }
        else if (dim)
        {
            row.AddChild(new TextureRect
            {
                Texture = _lockTex,
                Stretch = TextureRect.StretchMode.Scale,
                SetSize = new Vector2(15, 15),
                Modulate = conflicted ? ConflictStripe : LockedStripe,
                VerticalAlignment = VAlignment.Center,
            });
        }
        else
        {
            var badge = new HereticPoly(BadgeBg)
            {
                Octagon = true,
                Bevel = 5,
                VerticalAlignment = VAlignment.Center,
            };
            badge.AddChild(new Label
            {
                Text = node.Cost.ToString(),
                FontOverride = _fName,
                FontColorOverride = buyable ? GoldCol : DescCol,
                Margin = new Thickness(9, 2, 9, 2),
            });
            row.AddChild(badge);
        }

        card.AddChild(row);

        card.MouseFilter = MouseFilterMode.Pass;
        card.TooltipSupplier = _ => MakeTooltip(node, stripe);

        if (buyable)
        {
            card.Clickable = true;
            card.OnPressed += () => OnBuyPressed?.Invoke(node.Id);
        }

        return card;
    }
    private Control MakeTooltip(HereticStoreNode node, Color accent)
    {
        var box = new HereticPoly(TipBg)
        {
            BorderColor = accent,
            BorderWidth = 1.5f,
            Bevel = 8,
            MaxWidth = 280,
        };

        var col = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(12, 9, 12, 10),
        };

        col.AddChild(new Label
        {
            Text = Loc.GetString(node.Name),
            FontOverride = _fTipName,
            FontColorOverride = NameCol,
        });

        col.AddChild(new HereticPoly(TierLine)
        {
            Bevel = 0f,
            HorizontalExpand = true,
            MinSize = new Vector2(0, 1),
            Margin = new Thickness(0, 6, 0, 7),
        });

        var tipKey = node.Description.EndsWith("-desc")
            ? node.Description.Replace("-desc", "-tooltip")
            : node.Description;
        var body = Loc.TryGetString(tipKey, out var rich)
            ? rich
            : Loc.GetString(node.Description);

        var text = new RichTextLabel();
        text.SetMessage(FormattedMessage.FromMarkupPermissive(body), defaultColor: DescCol);
        col.AddChild(text);

        box.AddChild(col);
        return box;
    }
    private Control MakePlaceholder(string loc)
    {
        return new Label
        {
            Text = Loc.GetString(loc),
            FontOverride = _fDesc,
            FontColorOverride = LockedDesc,
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 16, 0, 0),
        };
    }

    private Control MakeTierLabel(int stage)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(2, 10, 2, 5),
        };

        row.AddChild(new Label
        {
            Text = Loc.GetString("heretic-store-tier", ("tier", stage)),
            FontOverride = _fTier,
            FontColorOverride = TierCol,
            VerticalAlignment = VAlignment.Center,
        });

        row.AddChild(new HereticPoly(TierLine)
        {
            Bevel = 0f,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            MinSize = new Vector2(0, 1),
            Margin = new Thickness(7, 0, 0, 0),
        });

        return row;
    }
}
